<a href="https://colab.research.google.com/github/azkaarahiilaa/Desain_dan_Analisis_Algoritma/blob/main/Tugas3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
aList = ["John", 33, "Toronto", True]
print(aList)


['John', 33, 'Toronto', True]


In [ ]:
import datetime

x= datetime.datetime.now()
print(x)

2023-09-11 06:15:08.676112


In [ ]:
mahasiswa = ["Azkaa Rh", 2022071052, "Informatika", "Desain Analisis Algoritma", x.strftime("%A" "%d" "%b" "%Y"), "Universitas pembangunan jaya"]
print (mahasiswa)

['Azkaa Rh', 2022071052, 'Informatika', 'Desain Analisis Algoritma', 'Monday11Sep2023', 'Universitas pembangunan jaya']


In [ ]:
bin_colors=['red', 'green', 'blue', 'yellow']
bin_colors[1]

'green'

In [ ]:
print (mahasiswa[1])

[2022071052, 'Informatika']


In [ ]:
print(mahasiswa[5])

UPJ


In [ ]:
bin_colors[0:2]

['red', 'green']

In [ ]:
print (mahasiswa[1:3])

[2022071052, 'Informatika']


In [ ]:
bin_colors=['red', 'green', 'blue', 'yellow']
for aColor in bin_colors:
  print("square", aColor)

square red
square green
square blue
square yellow


In [ ]:
for isi in mahasiswa :
  print ("UPJ", isi)

UPJ Azkaa Rh
UPJ 2022071052
UPJ Informatika
UPJ Desain Analisis Algoritma
UPJ Monday11Sep2023
UPJ Universitas pembangunan jaya


In [ ]:
bin_colors[2:]

['blue', 'yellow']

In [ ]:
UPJ=['Universitas', 'pembangunan', 'jaya']
UPJ[1:]

['pembangunan', 'jaya']

In [ ]:
hariAwal = ("senin", "selasa", "rabu")
hariAkhir = ("kamis", "jumat", "sabtu")

hari = (hariAwal, hariAkhir)
print(hari)

(('senin', 'selasa', 'rabu'), ('kamis', 'jumat', 'sabtu'))


In [ ]:
pertama=(100)
kedua=(200, 400, 600)
ketiga=(300)
keempat=(400, 800)

nested_tuple = (pertama, kedua, ketiga, keempat)
print (nested_tuple )

(100, (200, 400, 600), 300, (400, 800))


In [ ]:
bin_colors={
    "manual_color":"Yellow",
    "approved_color":"green",
    "refused_color":"red"
}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'green', 'refused_color': 'red'}


In [ ]:
siswa={
    "nama" : "azkaa",
    "NIM" : 2022071052,
    "prodi" : "Informatika",
    "universitas" : "upj"
}
print (siswa)

{'nama': 'azkaa', 'NIM': 2022071052, 'prodi': 'Informatika', 'universitas': 'upj'}


In [ ]:
#inisiasi set
set_01 = {4,5,6,2}
print (set_01)

#inisiasi mengubah list menjadi set
set_02 = set ()
set_03 = set ([2,1,4,3])

print(type(set_02))
print(set_03)

{2, 4, 5, 6}
<class 'set'>
{1, 2, 3, 4}


In [ ]:
set_A = {1,2,3,4}
set_B = {3,4,5,6}

print(set_A, set_B)
print(set_B.union(set_B))

{1, 2, 3, 4} {3, 4, 5, 6}
{3, 4, 5, 6}


In [45]:
# Membuat dua set yang berisi elemen-elemen yang diberikan
yellow = {'dandelions', 'fire hydrant', 'blood', 'rose', 'leaves'}
red = {'fire hydrant', 'blood', 'rose', 'leaves'}

# Menggunakan operator '&' untuk menghitung irisan antara kedua set
result = yellow & red

# Menampilkan hasil irisan
print(result)

{'blood', 'fire hydrant', 'leaves', 'rose'}


In [53]:
import pandas as pd
data = {
    'satu' : [1,1,1,1,1],
    'dua' : [2,2,2,2,2],
    'tiga' : [3,3,3,3,3]
}
df=pd.DataFrame(data, index = ['a', 'b', 'c', 'd', 'e'])
df.head()

satu  dua  tiga
a     1    2     3
b     1    2     3
c     1    2     3
d     1    2     3
e     1    2     3

In [51]:
import pandas as pd
mhs = ([
    ['1', 'Informatika', 50, 30, 20 ],
    ['2', 'Sistem Informasi', 55, 30, 25  ],
    ['3', 'Teknik Sipil', 40, 30, 10]]
)
df = pd.DataFrame(mhs)
df.columns =['No', 'Prodi', 'Mahasiswa', 'laki-laki', 'perempuan']
print(df)
print(df.columns)

  No             Prodi  Mahasiswa  laki-laki  perempuan
0  1       Informatika         50         30         20
1  2  Sistem Informasi         55         30         25
2  3      Teknik Sipil         40         30         10
Index(['No', 'Prodi', 'Mahasiswa', 'laki-laki', 'perempuan'], dtype='object')


In [60]:
import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)
[[11, 12, 13],
[21, 22, 23],
[31, 32, 33]]

print(type(myMatrix))


[[11 12 13]
 [21 22 23]
 [31 32 33]]
<class 'numpy.ndarray'>


In [61]:
print(type(myMatrix))

import numpy as np
matriksC = np.array([[1,2,3],
		     [4,5,6]])
print("Matriks C : ")
print(matriksC)

transpose_matriks = np.transpose(matriksC)

print("Tranpose Matriks C : ")
print(transpose_matriks)

<class 'numpy.ndarray'>
Matriks C : 
[[1 2 3]
 [4 5 6]]
Tranpose Matriks C : 
[[1 4]
 [2 5]
 [3 6]]


In [63]:
import numpy as np
matriksC = np.array ([[100, 200, 300],[700, 600, 500],[900, 1000, 800]])
print("Matriks A : ")
print(matriksC)

transpose_matriks = np.transpose(matriksC)

print("Tranpose Matriks A : ")
print(transpose_matriks)

Matriks A : 
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
Tranpose Matriks A : 
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [64]:
import numpy as np
matriksC = np.array ([[100, 200, 300],[700, 600, 500],[900, 1000, 800]])
print("Matriks C : ")
print(matriksC)

transpose_matriks = np.transpose(matriksC)

print("Tranpose Matriks C : ")
print(transpose_matriks)

Matriks C : 
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
Tranpose Matriks C : 
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [65]:
myVector = [22,33,44,55]
print(myVector)
[22,33,44,55]
print(type(myVector))

[22, 33, 44, 55]
<class 'list'>


In [68]:
 myVector = np.array([22,33,44,55])
print(myVector)
[22,33,44,55]
print(type(myVector))

[22 33 44 55]
<class 'numpy.ndarray'>


In [72]:
class stack :
    def _init_(self):
        self.items = []
    def isEmpety(self):
        return self.items==[]
    def push(self, items):
        self.items.appends(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.item[len(self.items)-1]
    def size(self):
        return len(self.items)



In [73]:
class Node:
    def __init__(self,data):
        self.left = None
        self.right = None
        self.data = data
    def PrintTree(self):
        if self.left:
            self.left.PrintTree()
        print( self.data),
        if self.right:
            self.right.PrintTree()

In [74]:
root = Node(2)#root
root.left = Node(3) #child kiri dari root
root.right = Node(5) #child kanan dari root
root.left.left = Node(7) #child kiri dari 3
root.left.right = Node(9) #child kanan dari 3
root.right.left = Node(11) #child kiri dari 5
root.right.right = Node(13) #child kanan dari 5
root.PrintTree()


7
3
9
2
11
5
13
